GET http://localhost:3003

###
POST http://localhost:3003/validator
Content-Type: application/json

{
  "name": "dfghj",
  "email": "johnx@ample.gi"
}

###
POST http://localhost:3003/regexp
Content-Type: application/json

{
  "name": "dfghj",
  "email": "kjdssdf@jsdfjk.cv"
}